import * as vscode from "vscode";
import { Project } from "../../models/project";
import { Roadmap } from "../../models/roadMap";
import { MarkdownExporter } from "./markdownExporter";
import { JsonExporter } from "./jsonExporter";
import { CsvExporter } from "./csvExporter";
import { ProgressTracker } from "../progress/progressTracker";
import { ServiceResult } from "../project/projectService";

const ok = <T>(data: T): ServiceResult<T> => ({ ok: true, data });
const fail = <T>(error: string): ServiceResult<T> => ({ ok: false, error });

export type ExportFormat = "markdown" | "json" | "csv-coverage" | "csv-tasks";


export class ExportService {
  private readonly markdownExporter: MarkdownExporter;
  private readonly jsonExporter: JsonExporter;
  private readonly csvExporter: CsvExporter;
  private readonly progressTracker: ProgressTracker;

  constructor() {
    this.markdownExporter = new MarkdownExporter();
    this.jsonExporter = new JsonExporter();
    this.csvExporter = new CsvExporter();
    this.progressTracker = new ProgressTracker();
  }

  async exportToFile(
    project: Project,
    roadmap: Roadmap | null,
    format: ExportFormat
  ): Promise<ServiceResult<vscode.Uri>> {
    // Generate content
    const content = this.generateContent(project, roadmap, format);
    const defaultName = this.defaultFileName(project, format);
    const fileFilter = this.fileFilter(format);

    // Show save dialog
    const uri = await vscode.window.showSaveDialog({
      defaultUri: vscode.Uri.file(defaultName),
      filters: fileFilter,
      title: `SBAtlas — Export as ${format}`,
    });

    if (!uri) {
      return fail("Export cancelled.");
    }

    // Write file
    try {
      const bytes = Buffer.from(content, "utf8");
      await vscode.workspace.fs.writeFile(uri, bytes);
      return ok(uri);
    } catch (error) {
      return fail(
        `Failed to write file: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }

  /**
   * Generates a progress summary string suitable for clipboard.
   */
  generateClipboardSummary(
    project: Project,
    roadmap: Roadmap | null
  ): string {
    const lines: string[] = [];

    lines.push(`📊 ${project.name}`);
    lines.push(`Status: ${project.status}`);
    lines.push(`Requirements: ${project.requirementCount()}`);

    if (roadmap && roadmap.phaseCount() > 0) {
      const summary = this.progressTracker.getSummary(roadmap);

      lines.push("");
      lines.push(
        `Progress: ${summary.completionPercentage}% ` +
          `(${summary.completedTasks}/${summary.totalTasks} tasks)`
      );

      if (summary.inProgressTasks > 0) {
        lines.push(`In Progress: ${summary.inProgressTasks} tasks`);
      }

      lines.push("");
      lines.push("Phases:");

      for (const phase of summary.phases) {
        lines.push(
          `  ${phase.completionPercentage === 100 ? "✅" : "📦"} ` +
            `Phase ${phase.phaseOrder}: ${phase.phaseTitle} — ` +
            `${phase.completionPercentage}%`
        );
      }

      if (summary.nextTask) {
        lines.push("");
        lines.push(`Next: ${summary.nextTask.title}`);
      }
    } else {
      lines.push("");
      lines.push("No roadmap generated yet.");
    }

    lines.push("");
    lines.push(`Generated by SBAtlas • ${new Date().toLocaleDateString()}`);

    return lines.join("\n");
  }

  // ─────────────────────────────────────────
  // Private helpers
  // ─────────────────────────────────────────

  private generateContent(
    project: Project,
    roadmap: Roadmap | null,
    format: ExportFormat
  ): string {
    switch (format) {
      case "markdown":
        return this.markdownExporter.export(project, roadmap);
      case "json":
        return this.jsonExporter.export(project, roadmap);
      case "csv-coverage":
        return this.csvExporter.exportCoverage(project, roadmap);
      case "csv-tasks":
        return this.csvExporter.exportTasks(roadmap);
    }
  }

  private defaultFileName(
    project: Project,
    format: ExportFormat
  ): string {
    const safeName = project.name
      .replace(/[^a-zA-Z0-9-_ ]/g, "")
      .replace(/\s+/g, "-")
      .toLowerCase();

    switch (format) {
      case "markdown":
        return `${safeName}-report.md`;
      case "json":
        return `${safeName}-export.json`;
      case "csv-coverage":
        return `${safeName}-coverage.csv`;
      case "csv-tasks":
        return `${safeName}-tasks.csv`;
    }
  }

  private fileFilter(
    format: ExportFormat
  ): Record<string, string[]> {
    switch (format) {
      case "markdown":
        return { Markdown: ["md"] };
      case "json":
        return { JSON: ["json"] };
      case "csv-coverage":
      case "csv-tasks":
        return { CSV: ["csv"] };
    }
  }
}