import { Project } from "../../models/project";
import { Roadmap } from "../../models/roadMap";
import { Phase } from "../../models/phase";
import { Module } from "../../models/module";
import { Task, TaskStatus } from "../../models/task";
import { ProgressTracker } from "../progress/progressTracker";
import { CoverageTracker } from "../coverage/coverageTracker";
import { RequirementCoverageStatus } from "../coverage/coverageTypes";

//   Generates a full project report as a Markdown string.
//   The document is structured for both human reading and
//   markdown renderers (GitHub, VS Code preview, Notion import).
export class MarkdownExporter {
  private readonly progressTracker: ProgressTracker;
  private readonly coverageTracker: CoverageTracker;

  constructor() {
    this.progressTracker = new ProgressTracker();
    this.coverageTracker = new CoverageTracker();
  }

//  Generates the complete markdown report.
  export(project: Project, roadmap: Roadmap | null): string {
    const sections: string[] = [];

    sections.push(this.buildHeader(project));
    sections.push(this.buildProjectOverview(project));
    sections.push(this.buildRequirementsSection(project));

    if (roadmap && roadmap.phaseCount() > 0) {
      sections.push(this.buildProgressSection(roadmap));
      sections.push(this.buildRoadmapSection(roadmap));
      sections.push(this.buildCoverageSection(project, roadmap));
    }

    sections.push(this.buildFooter());

    return sections.join("\n\n");
  }

  // Section builders

  private buildHeader(project: Project): string {
    return [
      `# ${project.name}`,
      "",
      `> Generated by SBAtlas on ${new Date().toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
      })}`,
    ].join("\n");
  }

  private buildProjectOverview(project: Project): string {
    const lines: string[] = [
      "## Project Overview",
      "",
    ];

    if (project.description) {
      lines.push(project.description, "");
    }

    lines.push(
      `| Field | Value |`,
      `|-------|-------|`,
      `| **Status** | ${project.status} |`,
      `| **Author** | ${project.metadata.author ?? "—"} |`,
      `| **Requirements** | ${project.requirementCount()} |`,
      `| **Created** | ${project.metadata.createdAt.toLocaleDateString()} |`,
      `| **Last Updated** | ${project.metadata.updatedAt.toLocaleDateString()} |`
    );

    return lines.join("\n");
  }

  private buildRequirementsSection(project: Project): string {
    const lines: string[] = [
      "## Requirements",
      "",
      `${project.requirementCount()} total requirements.`,
      "",
    ];

    if (project.requirements.length === 0) {
      lines.push("_No requirements defined._");
      return lines.join("\n");
    }

    for (const [index, req] of project.requirements.entries()) {
      const priorityIcon = this.priorityIcon(req.priority);
      const tagText =
        req.tags.length > 0
          ? ` \`${req.tags.join("` `")}\``
          : "";

      lines.push(
        `${index + 1}. ${priorityIcon} ${req.content}${tagText}`
      );
    }

    return lines.join("\n");
  }

  private buildProgressSection(roadmap: Roadmap): string {
    const summary = this.progressTracker.getSummary(roadmap);

    const lines: string[] = [
      "## Progress",
      "",
      `| Metric | Value |`,
      `|--------|-------|`,
      `| **Completion** | ${summary.completionPercentage}% |`,
      `| **Total Tasks** | ${summary.totalTasks} |`,
      `| **Completed** | ${summary.completedTasks} |`,
      `| **In Progress** | ${summary.inProgressTasks} |`,
      `| **Pending** | ${summary.pendingTasks} |`,
      `| **Skipped** | ${summary.skippedTasks} |`,
    ];

    if (summary.remainingEffort > 0) {
      lines.push(
        `| **Remaining Effort** | ${summary.remainingEffort} points |`
      );
    }

    // Progress bar
    lines.push("");
    lines.push(this.progressBar(summary.completionPercentage));

    // Per-phase summary
    lines.push("", "### Phase Progress", "");

    for (const phase of summary.phases) {
      lines.push(
        `- **Phase ${phase.phaseOrder}: ${phase.phaseTitle}** — ` +
          `${phase.completionPercentage}% ` +
          `(${phase.completedTasks}/${phase.totalTasks} tasks)`
      );
    }

    // Task type breakdown
    if (summary.tasksByType.length > 0) {
      lines.push("", "### Tasks by Type", "");
      lines.push(`| Type | Done | Total | % |`);
      lines.push(`|------|------|-------|---|`);

      for (const t of summary.tasksByType) {
        lines.push(
          `| ${t.type} | ${t.completedTasks} | ${t.totalTasks} | ${t.completionPercentage}% |`
        );
      }
    }

    return lines.join("\n");
  }

  private buildRoadmapSection(roadmap: Roadmap): string {
    const lines: string[] = ["## Roadmap", ""];

    for (const phase of roadmap.phases) {
      lines.push(
        `### Phase ${phase.order}: ${phase.title}`
      );
      lines.push("");

      if (phase.description) {
        lines.push(`_${phase.description}_`, "");
      }

      for (const module of phase.modules) {
        lines.push(
          `#### ${module.title} ` +
            `(${module.completionPercentage()}%)`
        );
        lines.push("");

        if (module.description) {
          lines.push(`_${module.description}_`, "");
        }

        for (const task of module.tasks) {
          const icon = this.taskStatusIcon(task.status);
          const effort = task.estimatedEffort
            ? ` _(${task.estimatedEffort}pts)_`
            : "";
          const blocked =
            task.blockedBy.length > 0 ? " ⛔" : "";

          lines.push(
            `- ${icon} **${task.title}**${effort}${blocked}`
          );

          if (task.description) {
            lines.push(`  ${task.description}`);
          }

          if (task.notes) {
            lines.push(`  > ${task.notes.replace(/\n/g, "\n  > ")}`);
          }
        }

        lines.push("");
      }
    }

    return lines.join("\n");
  }

  private buildCoverageSection(
    project: Project,
    roadmap: Roadmap
  ): string {
    const report = this.coverageTracker.getReport(project, roadmap);

    const lines: string[] = [
      "## Coverage",
      "",
      `| Metric | Value |`,
      `|--------|-------|`,
      `| **Coverage** | ${report.coveragePercentage}% |`,
      `| **Addressable** | ${report.addressablePercentage}% |`,
      `| **Covered** | ${report.coveredCount} |`,
      `| **Partial** | ${report.partialCount} |`,
      `| **Uncovered** | ${report.uncoveredCount} |`,
      `| **Orphan Tasks** | ${report.orphanTasks.length} |`,
      "",
      "### Per-Requirement Coverage",
      "",
      "| # | Requirement | Status | Tasks |",
      "|---|-------------|--------|-------|",
    ];

    for (const [index, rc] of report.requirements.entries()) {
      const icon = this.coverageIcon(rc.status);
      const content =
        rc.requirement.content.length > 60
          ? rc.requirement.content.slice(0, 60).trimEnd() + "…"
          : rc.requirement.content;

      lines.push(
        `| ${index + 1} | ${icon} ${content} | ${rc.status} | ${rc.tasks.length} |`
      );
    }

    if (report.orphanTasks.length > 0) {
      lines.push(
        "",
        "### Orphan Tasks (no requirement link)",
        ""
      );

      for (const orphan of report.orphanTasks) {
        lines.push(
          `- ⚠ **${orphan.task.title}** _(${orphan.phaseName} → ${orphan.moduleName})_`
        );
      }
    }

    if (report.warnings.length > 0) {
      lines.push("", "### Warnings", "");
      for (const warning of report.warnings) {
        lines.push(`- ${warning}`);
      }
    }

    return lines.join("\n");
  }

  private buildFooter(): string {
    return [
      "---",
      "",
      `_Report generated by [SBAtlas](https://github.com/sbatlas) ` +
        `on ${new Date().toISOString()}_`,
    ].join("\n");
  }

  // Helpers
  private priorityIcon(priority: string): string {
    const icons: Record<string, string> = {
      high: "🔴",
      medium: "🟡",
      low: "🟢",
    };
    return icons[priority] ?? "🟡";
  }

  private taskStatusIcon(status: TaskStatus): string {
    const icons: Record<TaskStatus, string> = {
      [TaskStatus.Pending]: "⬜",
      [TaskStatus.InProgress]: "🔶",
      [TaskStatus.Done]: "✅",
      [TaskStatus.Skipped]: "⏭️",
    };
    return icons[status];
  }

  private coverageIcon(status: RequirementCoverageStatus): string {
    const icons: Record<RequirementCoverageStatus, string> = {
      [RequirementCoverageStatus.Covered]: "✅",
      [RequirementCoverageStatus.Partial]: "🔶",
      [RequirementCoverageStatus.Uncovered]: "❌",
    };
    return icons[status];
  }

  private progressBar(percentage: number): string {
    const filled = Math.round(percentage / 5);
    const empty = 20 - filled;
    return `\`[${"█".repeat(filled)}${"░".repeat(empty)}]\` ${percentage}%`;
  }
}